add authentication to swagger
SergiLomtadze/SERGI_LOMTADZE_INDIVIDUAL_MENTORSHIP pull request #101
Opened 2022-06-10 19:59 UTC by SergiLomtadze

2022-06-11 11:39 UTC, SergiLomtadze commented
Problem was in IdentityModel nuget version, I solved it, now it's working as should be

2022-06-11 12:21 UTC, kdavletov-exadel requested changes

2022-06-11 12:21 UTC, kdavletov-exadel commented on src/ExadelMentorship.WebApi/Controllers/LoginController.cs
> +        [HttpPost("token/{userName}/{password}")]
Pass from body, not query

2022-06-11 12:21 UTC, kdavletov-exadel commented on src/ExadelMentorship.WebApi/Token/TokenService .cs
> +                _discDocument = client.GetDiscoveryDocumentAsync("https://localhost:7162/.well-known/openid-configuration").Result;
1. Url to config;
2. Avoid Task.Result

2022-06-11 12:59 UTC, SergiLomtadze commented on src/ExadelMentorship.WebApi/Controllers/LoginController.cs
> +        [HttpPost("token/{userName}/{password}")]
done

2022-06-11 13:00 UTC, SergiLomtadze commented on src/ExadelMentorship.WebApi/Token/TokenService .cs
> +                _discDocument = client.GetDiscoveryDocumentAsync("https://localhost:7162/.well-known/openid-configuration").Result;
done

2022-06-11 14:29 UTC, kdavletov-exadel requested changes
Fix the warnings and you are set

2022-06-11 17:44 UTC, SergiLomtadze commented
> you are set

done

2022-06-11 17:48 UTC, kdavletov-exadel requested changes

2022-06-11 17:48 UTC, kdavletov-exadel commented on src/ExadelMentorship.Auth/IdentityConfiguration.cs
> +                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
Think of how to use Authorization Code + PKCE.

2022-06-13 10:08 UTC, SergiLomtadze commented
PR size is failing because of Auth default staff (Quickstart) changes are huge .
I deleted all not needed views.

2022-06-13 10:32 UTC, kdavletov-exadel requested changes
Also, fix the PR warnings.

2022-06-13 10:32 UTC, kdavletov-exadel commented on src/ExadelMentorship.Auth/IdentityConfiguration.cs
> +                RedirectUris = { "https://localhost:7066/swagger/oauth2-redirect.html" },
base url to config

2022-06-13 10:32 UTC, kdavletov-exadel commented on src/ExadelMentorship.Auth/IdentityConfiguration.cs
> +                AllowedCorsOrigins = { "https://localhost:7066" },
same

2022-06-13 10:32 UTC, kdavletov-exadel commented on src/ExadelMentorship.WebApi/Program.cs
> +        o.Authority = "https://localhost:7046";
config

2022-06-13 12:19 UTC, SergiLomtadze commented on src/ExadelMentorship.WebApi/Program.cs
> +        o.Authority = "https://localhost:7046";
done

2022-06-13 12:19 UTC, SergiLomtadze commented on src/ExadelMentorship.Auth/IdentityConfiguration.cs
> +                AllowedCorsOrigins = { "https://localhost:7066" },
can't use IOptions inside static method

2022-06-13 12:20 UTC, SergiLomtadze commented on src/ExadelMentorship.Auth/IdentityConfiguration.cs
> +                RedirectUris = { "https://localhost:7066/swagger/oauth2-redirect.html" },
can't use IOptions inside static method

2022-06-13 12:21 UTC, kdavletov-exadel approved these changes

2022-06-13 12:24 UTC, merged