call api from job, publish from api
SergiLomtadze/SERGI_LOMTADZE_INDIVIDUAL_MENTORSHIP pull request #119
Opened 2022-07-04 14:21 UTC by SergiLomtadze

2022-07-04 14:26 UTC, kdavletov-exadel requested changes

2022-07-04 14:26 UTC, kdavletov-exadel commented on src/ExadelMentorship.Jobs/ReportJob.cs
> +            var url = $"http://localhost:5066/api/Message/SendMail";
config

2022-07-04 15:44 UTC, kdavletov-exadel requested changes

2022-07-04 15:50 UTC, SergiLomtadze commented on src/ExadelMentorship.Jobs/ReportJob.cs
> +            var url = $"http://localhost:5066/api/Message/SendMail";
done

2022-07-05 09:01 UTC, kdavletov-exadel approved these changes

2022-07-05 09:13 UTC, merged